# Generated by Django 4.2 on 2024-04-23 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_product_release_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='release_date',
        ),
    ]
